name: test-workflow
on: push
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
     
          - name: Run tests
            run: echo "Running tests buddy it is done"
          - name: 'exist node-version:'
            run: node -v
          - name: Install node
            uses: actions/setup-node@v4
            with:
              node-version: 20
          - name : consoling node-version
            run: node -v